### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by KMEHSilhouette**
A Chinese translation has been reviewed and tested many times lol

### CODE REVIEW

**Comment by Un-Original1** [comment]
Great! I'll introduce it asap, I'll let you know if I need anything

**Comment by Un-Original1** [comment]
As a new update is being worked on I might require some other stuff to translate, It could be great if we got a translation of these as it would look weird to have a sort of unfinished translation, here are the new entries:

[new_entries.txt](https://github.com/Un-Original1/AncientBeasts/files/8217079/new_entries.txt)

**Comment by KMEHSilhouette** [comment]
Actually your mod gets lot of potential, so I can work as an offically translator for a long term lol.

**Comment by KMEHSilhouette** [comment]
Here is the cn translation. By the way , can you give me a glance of owlstack? I want to make sure whether my translation is accurate
[new_entries cn.txt](https://github.com/Un-Original1/AncientBeasts/files/8222905/new_entries.cn.txt)
.

**Comment by Un-Original1** [comment]
Thanks! your translation will be added next update, also, this is an owlstack, an alternate name to it was owl pile
image

**Comment by Un-Original1** [comment]
Hey, so it has been a while and turns out this is also needed to be translated, I tried contacting you via discord but got no response, however, if you are avaliable, can you translate these new entries? Update is about to release and this is all what's missing, I will update the mod in a few days so it would be nice to have the lang files complete.
[lastlangsbeforeupdate.txt](https://github.com/Un-Original1/AncientBeasts/files/8535454/lastlangsbeforeupdate.txt)

**Pull request closed without merging**
